name: Go Install Check

on:
  push:
    branches: [main]
    paths-ignore:
        - .gitignore
        - README.md
        - LICENSE
        - TODO
        - Dockerfile
        - images/*

  pull_request:
    branches: [main]
    paths-ignore:
        - .gitignore
        - README.md
        - LICENSE
        - TODO
        - Dockerfile
        - images/*

  #schedule:
  #  - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            ca-certificates jq curl

      - name: Install infrachart at specific commit
        run: |
          go install github.com/helviojunior/infrachart@${GITHUB_SHA}

      - name: Create a fake wordlist
        run: |
          cat << EOF > /tmp/wl.txt
          www
          wiki
          EOF

      - name: Verify Installation
        run: |
          infrachart version
          
